if(BOOP_USE_MOCKTURTLE)
  add_executable(mockturtle_mapping_test mockturtle_mapping.cpp)
  target_link_libraries(mockturtle_mapping_test PRIVATE boop::mockturtle_interface mockturtle)
  add_test(NAME mockturtle_mapping COMMAND mockturtle_mapping_test)
endif()

if(NOT BOOP_BUILD_PROGRAMS)
  return()
endif()

file(GLOB BOOP_BENCHMARKS CONFIGURE_DEPENDS benchmarks/*.aig)
foreach(BOOP_BENCHMARK ${BOOP_BENCHMARKS})
  get_filename_component(BOOP_TEST_NAME ${BOOP_BENCHMARK} NAME_WE)
  set(BOOP_FAST_TEST_ARGS
    -DTEST_NAME=fast_${BOOP_TEST_NAME}
    -DFAST_EXECUTABLE=$<TARGET_FILE:fast>
    -DINPUT_PATH=${BOOP_BENCHMARK}
    -DOUTPUT_PATH=${CMAKE_CURRENT_BINARY_DIR}/${BOOP_TEST_NAME}.fast.aig
  )
  set(BOOP_HELO_TEST_ARGS
    -DTEST_NAME=helo_${BOOP_TEST_NAME}
    -DHELO_EXECUTABLE=$<TARGET_FILE:helo>
    -DINPUT_PATH=${BOOP_BENCHMARK}
    -DOUTPUT_PATH=${CMAKE_CURRENT_BINARY_DIR}/${BOOP_TEST_NAME}.helo.aig
  )

  if(BOOP_USE_ABC)
    list(APPEND BOOP_FAST_TEST_ARGS
      -DABC_EXECUTABLE=$<TARGET_FILE:abc>
    )
    list(APPEND BOOP_HELO_TEST_ARGS
      -DABC_EXECUTABLE=$<TARGET_FILE:abc>
    )
  endif()

  add_test(NAME fast_${BOOP_TEST_NAME}
    COMMAND ${CMAKE_COMMAND}
      ${BOOP_FAST_TEST_ARGS}
      -P ${CMAKE_CURRENT_SOURCE_DIR}/run_fast.cmake
  )
  add_test(NAME helo_${BOOP_TEST_NAME}
    COMMAND ${CMAKE_COMMAND}
      ${BOOP_HELO_TEST_ARGS}
      -P ${CMAKE_CURRENT_SOURCE_DIR}/run_helo.cmake
  )
endforeach()
